// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tagatac/bagoup/v2/imgconvert (interfaces: ImgConverter)
//
// Generated by this command:
//
//	mockgen -destination=mock_imgconvert/mock_imgconvert.go github.com/tagatac/bagoup/v2/imgconvert ImgConverter
//

// Package mock_imgconvert is a generated GoMock package.
package mock_imgconvert

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImgConverter is a mock of ImgConverter interface.
type MockImgConverter struct {
	ctrl     *gomock.Controller
	recorder *MockImgConverterMockRecorder
	isgomock struct{}
}

// MockImgConverterMockRecorder is the mock recorder for MockImgConverter.
type MockImgConverterMockRecorder struct {
	mock *MockImgConverter
}

// NewMockImgConverter creates a new mock instance.
func NewMockImgConverter(ctrl *gomock.Controller) *MockImgConverter {
	mock := &MockImgConverter{ctrl: ctrl}
	mock.recorder = &MockImgConverterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImgConverter) EXPECT() *MockImgConverterMockRecorder {
	return m.recorder
}

// ConvertHEIC mocks base method.
func (m *MockImgConverter) ConvertHEIC(src string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConvertHEIC", src)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConvertHEIC indicates an expected call of ConvertHEIC.
func (mr *MockImgConverterMockRecorder) ConvertHEIC(src any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConvertHEIC", reflect.TypeOf((*MockImgConverter)(nil).ConvertHEIC), src)
}
