language: go
go:
  - 1.x
before_install:
  - sudo apt-get -y install wkhtmltopdf xvfb
  - alias wkhtmltopdf='xvfb-run wkhtmltopdf'
install:
  - go mod download
script:
  - make test
after_success:
  - make codecov
