coverage:
  status:
    project:
      default:
        threshold: 0.2%
    patch:
      default:
        threshold: 2%
ignore:
  - cmd/bagoup/main.go
  - example-exports/examplegen.go
  - opsys/pdfgen/pdfgen.go
  - opsys/scall/scall.go
