// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tagatac/bagoup/v2/pathtools (interfaces: PathTools)
//
// Generated by this command:
//
//	mockgen -destination=mock_pathtools/mock_pathtools.go github.com/tagatac/bagoup/v2/pathtools PathTools
//

// Package mock_pathtools is a generated GoMock package.
package mock_pathtools

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPathTools is a mock of PathTools interface.
type MockPathTools struct {
	ctrl     *gomock.Controller
	recorder *MockPathToolsMockRecorder
	isgomock struct{}
}

// MockPathToolsMockRecorder is the mock recorder for MockPathTools.
type MockPathToolsMockRecorder struct {
	mock *MockPathTools
}

// NewMockPathTools creates a new mock instance.
func NewMockPathTools(ctrl *gomock.Controller) *MockPathTools {
	mock := &MockPathTools{ctrl: ctrl}
	mock.recorder = &MockPathToolsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPathTools) EXPECT() *MockPathToolsMockRecorder {
	return m.recorder
}

// GetHomeDir mocks base method.
func (m *MockPathTools) GetHomeDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHomeDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetHomeDir indicates an expected call of GetHomeDir.
func (mr *MockPathToolsMockRecorder) GetHomeDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHomeDir", reflect.TypeOf((*MockPathTools)(nil).GetHomeDir))
}

// ReplaceTilde mocks base method.
func (m *MockPathTools) ReplaceTilde(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceTilde", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// ReplaceTilde indicates an expected call of ReplaceTilde.
func (mr *MockPathToolsMockRecorder) ReplaceTilde(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceTilde", reflect.TypeOf((*MockPathTools)(nil).ReplaceTilde), filePath)
}
