// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tagatac/bagoup/v2/chatdb (interfaces: ChatDB)
//
// Generated by this command:
//
//	mockgen -destination=mock_chatdb/mock_chatdb.go github.com/tagatac/bagoup/v2/chatdb ChatDB
//

// Package mock_chatdb is a generated GoMock package.
package mock_chatdb

import (
	reflect "reflect"

	semver "github.com/Masterminds/semver"
	go_vcard "github.com/emersion/go-vcard"
	chatdb "github.com/tagatac/bagoup/v2/chatdb"
	pathtools "github.com/tagatac/bagoup/v2/pathtools"
	gomock "go.uber.org/mock/gomock"
)

// MockChatDB is a mock of ChatDB interface.
type MockChatDB struct {
	ctrl     *gomock.Controller
	recorder *MockChatDBMockRecorder
	isgomock struct{}
}

// MockChatDBMockRecorder is the mock recorder for MockChatDB.
type MockChatDBMockRecorder struct {
	mock *MockChatDB
}

// NewMockChatDB creates a new mock instance.
func NewMockChatDB(ctrl *gomock.Controller) *MockChatDB {
	mock := &MockChatDB{ctrl: ctrl}
	mock.recorder = &MockChatDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatDB) EXPECT() *MockChatDBMockRecorder {
	return m.recorder
}

// GetAttachmentPaths mocks base method.
func (m *MockChatDB) GetAttachmentPaths(ptools pathtools.PathTools) (map[int][]chatdb.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentPaths", ptools)
	ret0, _ := ret[0].(map[int][]chatdb.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachmentPaths indicates an expected call of GetAttachmentPaths.
func (mr *MockChatDBMockRecorder) GetAttachmentPaths(ptools any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentPaths", reflect.TypeOf((*MockChatDB)(nil).GetAttachmentPaths), ptools)
}

// GetChats mocks base method.
func (m *MockChatDB) GetChats(contactMap map[string]*go_vcard.Card) ([]chatdb.EntityChats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChats", contactMap)
	ret0, _ := ret[0].([]chatdb.EntityChats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChats indicates an expected call of GetChats.
func (mr *MockChatDBMockRecorder) GetChats(contactMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChats", reflect.TypeOf((*MockChatDB)(nil).GetChats), contactMap)
}

// GetHandleMap mocks base method.
func (m *MockChatDB) GetHandleMap(contactMap map[string]*go_vcard.Card) (map[int]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandleMap", contactMap)
	ret0, _ := ret[0].(map[int]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHandleMap indicates an expected call of GetHandleMap.
func (mr *MockChatDBMockRecorder) GetHandleMap(contactMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandleMap", reflect.TypeOf((*MockChatDB)(nil).GetHandleMap), contactMap)
}

// GetMessage mocks base method.
func (m *MockChatDB) GetMessage(messageID int, handleMap map[int]string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", messageID, handleMap)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockChatDBMockRecorder) GetMessage(messageID, handleMap any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockChatDB)(nil).GetMessage), messageID, handleMap)
}

// GetMessageIDs mocks base method.
func (m *MockChatDB) GetMessageIDs(chatID int) ([]chatdb.DatedMessageID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageIDs", chatID)
	ret0, _ := ret[0].([]chatdb.DatedMessageID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageIDs indicates an expected call of GetMessageIDs.
func (mr *MockChatDBMockRecorder) GetMessageIDs(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageIDs", reflect.TypeOf((*MockChatDB)(nil).GetMessageIDs), chatID)
}

// Init mocks base method.
func (m *MockChatDB) Init(macOSVersion *semver.Version) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", macOSVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockChatDBMockRecorder) Init(macOSVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockChatDB)(nil).Init), macOSVersion)
}
