// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tagatac/bagoup/v2/opsys/scall (interfaces: Syscall)
//
// Generated by this command:
//
//	mockgen -destination=mock_scall/mock_scall.go github.com/tagatac/bagoup/v2/opsys/scall Syscall
//

// Package mock_scall is a generated GoMock package.
package mock_scall

import (
	reflect "reflect"
	syscall "syscall"

	gomock "go.uber.org/mock/gomock"
)

// MockSyscall is a mock of Syscall interface.
type MockSyscall struct {
	ctrl     *gomock.Controller
	recorder *MockSyscallMockRecorder
	isgomock struct{}
}

// MockSyscallMockRecorder is the mock recorder for MockSyscall.
type MockSyscallMockRecorder struct {
	mock *MockSyscall
}

// NewMockSyscall creates a new mock instance.
func NewMockSyscall(ctrl *gomock.Controller) *MockSyscall {
	mock := &MockSyscall{ctrl: ctrl}
	mock.recorder = &MockSyscallMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyscall) EXPECT() *MockSyscallMockRecorder {
	return m.recorder
}

// Getrlimit mocks base method.
func (m *MockSyscall) Getrlimit(which int, lim *syscall.Rlimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getrlimit", which, lim)
	ret0, _ := ret[0].(error)
	return ret0
}

// Getrlimit indicates an expected call of Getrlimit.
func (mr *MockSyscallMockRecorder) Getrlimit(which, lim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getrlimit", reflect.TypeOf((*MockSyscall)(nil).Getrlimit), which, lim)
}

// Setrlimit mocks base method.
func (m *MockSyscall) Setrlimit(which int, lim *syscall.Rlimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Setrlimit", which, lim)
	ret0, _ := ret[0].(error)
	return ret0
}

// Setrlimit indicates an expected call of Setrlimit.
func (mr *MockSyscallMockRecorder) Setrlimit(which, lim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Setrlimit", reflect.TypeOf((*MockSyscall)(nil).Setrlimit), which, lim)
}
