/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: pdf.i

package pdf

// #cgo CFLAGS: -I.
/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef _gostring_ swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef void* swig_type_10;
typedef void* swig_type_11;
typedef void* swig_type_12;
typedef void* swig_type_13;
typedef void* swig_type_14;
typedef void* swig_type_15;
typedef void* swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef long long swig_type_20;
extern void _wrap_Swig_free_pdf_b6543bab41504ff7(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_pdf_b6543bab41504ff7(swig_intgo arg1);
extern swig_intgo _wrap_wkhtmltopdf_init_pdf_b6543bab41504ff7(swig_intgo arg1);
extern swig_intgo _wrap_wkhtmltopdf_deinit_pdf_b6543bab41504ff7(void);
extern swig_intgo _wrap_wkhtmltopdf_extended_qt_pdf_b6543bab41504ff7(void);
extern swig_type_1 _wrap_wkhtmltopdf_version_pdf_b6543bab41504ff7(void);
extern uintptr_t _wrap_wkhtmltopdf_create_global_settings_pdf_b6543bab41504ff7(void);
extern void _wrap_wkhtmltopdf_destroy_global_settings_pdf_b6543bab41504ff7(uintptr_t arg1);
extern uintptr_t _wrap_wkhtmltopdf_create_object_settings_pdf_b6543bab41504ff7(void);
extern void _wrap_wkhtmltopdf_destroy_object_settings_pdf_b6543bab41504ff7(uintptr_t arg1);
extern swig_intgo _wrap_wkhtmltopdf_set_global_setting_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_2 arg2, swig_type_3 arg3);
extern swig_intgo _wrap_wkhtmltopdf_get_global_setting_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_4 arg2, swig_type_5 arg3, swig_intgo arg4);
extern swig_intgo _wrap_wkhtmltopdf_set_object_setting_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_6 arg2, swig_type_7 arg3);
extern swig_intgo _wrap_wkhtmltopdf_get_object_setting_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_8 arg2, swig_type_9 arg3, swig_intgo arg4);
extern uintptr_t _wrap_wkhtmltopdf_create_converter_pdf_b6543bab41504ff7(uintptr_t arg1);
extern void _wrap_wkhtmltopdf_destroy_converter_pdf_b6543bab41504ff7(uintptr_t arg1);
extern void _wrap_wkhtmltopdf_set_debug_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_10 arg2);
extern void _wrap_wkhtmltopdf_set_info_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_11 arg2);
extern void _wrap_wkhtmltopdf_set_warning_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_12 arg2);
extern void _wrap_wkhtmltopdf_set_error_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_13 arg2);
extern void _wrap_wkhtmltopdf_set_phase_changed_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_14 arg2);
extern void _wrap_wkhtmltopdf_set_progress_changed_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_15 arg2);
extern void _wrap_wkhtmltopdf_set_finished_callback_pdf_b6543bab41504ff7(uintptr_t arg1, swig_type_16 arg2);
extern swig_intgo _wrap_wkhtmltopdf_convert_pdf_b6543bab41504ff7(uintptr_t arg1);
extern void _wrap_wkhtmltopdf_add_object_pdf_b6543bab41504ff7(uintptr_t arg1, uintptr_t arg2, swig_type_17 arg3);
extern swig_intgo _wrap_wkhtmltopdf_current_phase_pdf_b6543bab41504ff7(uintptr_t arg1);
extern swig_intgo _wrap_wkhtmltopdf_phase_count_pdf_b6543bab41504ff7(uintptr_t arg1);
extern swig_type_18 _wrap_wkhtmltopdf_phase_description_pdf_b6543bab41504ff7(uintptr_t arg1, swig_intgo arg2);
extern swig_type_19 _wrap_wkhtmltopdf_progress_string_pdf_b6543bab41504ff7(uintptr_t arg1);
extern swig_intgo _wrap_wkhtmltopdf_http_error_code_pdf_b6543bab41504ff7(uintptr_t arg1);
extern swig_type_20 _wrap_wkhtmltopdf_get_output_pdf_b6543bab41504ff7(uintptr_t arg1, swig_voidp arg2);
#undef intgo
*/
import "C"

import (
	_ "runtime/cgo"
	"sync"
	"unsafe"
)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

type swig_gostring struct {
	p uintptr
	n int
}

func swigCopyString(s string) string {
	p := *(*swig_gostring)(unsafe.Pointer(&s))
	r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
	Swig_free(p.p)
	return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_pdf_b6543bab41504ff7(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Wkhtmltopdf_init(arg1 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1
	swig_r = (int)(C._wrap_wkhtmltopdf_init_pdf_b6543bab41504ff7(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Wkhtmltopdf_deinit() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_wkhtmltopdf_deinit_pdf_b6543bab41504ff7())
	return swig_r
}

func Wkhtmltopdf_extended_qt() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_wkhtmltopdf_extended_qt_pdf_b6543bab41504ff7())
	return swig_r
}

func Wkhtmltopdf_version() (_swig_ret string) {
	var swig_r string
	swig_r_p := C._wrap_wkhtmltopdf_version_pdf_b6543bab41504ff7()
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func Wkhtmltopdf_create_global_settings() (_swig_ret Wkhtmltopdf_global_settings) {
	var swig_r Wkhtmltopdf_global_settings
	swig_r = (Wkhtmltopdf_global_settings)(SwigcptrWkhtmltopdf_global_settings(C._wrap_wkhtmltopdf_create_global_settings_pdf_b6543bab41504ff7()))
	return swig_r
}

func Wkhtmltopdf_destroy_global_settings(arg1 Wkhtmltopdf_global_settings) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_wkhtmltopdf_destroy_global_settings_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0))
}

func Wkhtmltopdf_create_object_settings() (_swig_ret Wkhtmltopdf_object_settings) {
	var swig_r Wkhtmltopdf_object_settings
	swig_r = (Wkhtmltopdf_object_settings)(SwigcptrWkhtmltopdf_object_settings(C._wrap_wkhtmltopdf_create_object_settings_pdf_b6543bab41504ff7()))
	return swig_r
}

func Wkhtmltopdf_destroy_object_settings(arg1 Wkhtmltopdf_object_settings) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_wkhtmltopdf_destroy_object_settings_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0))
}

func Wkhtmltopdf_set_global_setting(arg1 Wkhtmltopdf_global_settings, arg2 string, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_wkhtmltopdf_set_global_setting_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Wkhtmltopdf_get_global_setting(arg1 Wkhtmltopdf_global_settings, arg2 string, arg3 string, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_wkhtmltopdf_get_global_setting_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Wkhtmltopdf_set_object_setting(arg1 Wkhtmltopdf_object_settings, arg2 string, arg3 string) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	swig_r = (int)(C._wrap_wkhtmltopdf_set_object_setting_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_2))))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Wkhtmltopdf_get_object_setting(arg1 Wkhtmltopdf_object_settings, arg2 string, arg3 string, arg4 int) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	swig_r = (int)(C._wrap_wkhtmltopdf_get_object_setting_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_1)), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_2)), C.swig_intgo(_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
	return swig_r
}

func Wkhtmltopdf_create_converter(arg1 Wkhtmltopdf_global_settings) (_swig_ret Wkhtmltopdf_converter) {
	var swig_r Wkhtmltopdf_converter
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (Wkhtmltopdf_converter)(SwigcptrWkhtmltopdf_converter(C._wrap_wkhtmltopdf_create_converter_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func Wkhtmltopdf_destroy_converter(arg1 Wkhtmltopdf_converter) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_wkhtmltopdf_destroy_converter_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0))
}

func Wkhtmltopdf_set_debug_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_debug_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_10(_swig_i_1))
}

func Wkhtmltopdf_set_info_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_info_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_11(_swig_i_1))
}

func Wkhtmltopdf_set_warning_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_warning_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_12(_swig_i_1))
}

func Wkhtmltopdf_set_error_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_error_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_13(_swig_i_1))
}

func Wkhtmltopdf_set_phase_changed_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_phase_changed_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_14(_swig_i_1))
}

func Wkhtmltopdf_set_progress_changed_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_progress_changed_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_15(_swig_i_1))
}

func Wkhtmltopdf_set_finished_callback(arg1 Wkhtmltopdf_converter, arg2 _swig_fnptr) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	C._wrap_wkhtmltopdf_set_finished_callback_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_type_16(_swig_i_1))
}

func Wkhtmltopdf_convert(arg1 Wkhtmltopdf_converter) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_wkhtmltopdf_convert_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wkhtmltopdf_add_object(arg1 Wkhtmltopdf_converter, arg2 Wkhtmltopdf_object_settings, arg3 string) {
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2.Swigcptr()
	_swig_i_2 := arg3
	C._wrap_wkhtmltopdf_add_object_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_2)))
	if Swig_escape_always_false {
		Swig_escape_val = arg3
	}
}

func Wkhtmltopdf_current_phase(arg1 Wkhtmltopdf_converter) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_wkhtmltopdf_current_phase_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wkhtmltopdf_phase_count(arg1 Wkhtmltopdf_converter) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_wkhtmltopdf_phase_count_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wkhtmltopdf_phase_description(arg1 Wkhtmltopdf_converter, arg2 int) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r_p := C._wrap_wkhtmltopdf_phase_description_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func Wkhtmltopdf_progress_string(arg1 Wkhtmltopdf_converter) (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1.Swigcptr()
	swig_r_p := C._wrap_wkhtmltopdf_progress_string_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
	swig_r_1 = swigCopyString(swig_r)
	return swig_r_1
}

func Wkhtmltopdf_http_error_code(arg1 Wkhtmltopdf_converter) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_wkhtmltopdf_http_error_code_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Wkhtmltopdf_get_output(arg1 Wkhtmltopdf_converter, arg2 **byte) (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1.Swigcptr()
	_swig_i_1 := arg2
	swig_r = (int64)(C._wrap_wkhtmltopdf_get_output_pdf_b6543bab41504ff7(C.uintptr_t(_swig_i_0), C.swig_voidp(_swig_i_1)))
	return swig_r
}

type SwigcptrWkhtmltopdf_converter uintptr
type Wkhtmltopdf_converter interface {
	Swigcptr() uintptr
}

func (p SwigcptrWkhtmltopdf_converter) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrWkhtmltopdf_global_settings uintptr
type Wkhtmltopdf_global_settings interface {
	Swigcptr() uintptr
}

func (p SwigcptrWkhtmltopdf_global_settings) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrWkhtmltopdf_object_settings uintptr
type Wkhtmltopdf_object_settings interface {
	Swigcptr() uintptr
}

func (p SwigcptrWkhtmltopdf_object_settings) Swigcptr() uintptr {
	return uintptr(p)
}
