/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: pdf.i */

#define SWIGMODULE pdf
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


struct wkhtmltopdf_global_settings;
typedef struct wkhtmltopdf_global_settings wkhtmltopdf_global_settings;

struct wkhtmltopdf_object_settings;
typedef struct wkhtmltopdf_object_settings wkhtmltopdf_object_settings;

struct wkhtmltopdf_converter;
typedef struct wkhtmltopdf_converter wkhtmltopdf_converter;

typedef void (*wkhtmltopdf_str_callback)(wkhtmltopdf_converter * converter, const char * str);
typedef void (*wkhtmltopdf_int_callback)(wkhtmltopdf_converter * converter, const int val);
typedef void (*wkhtmltopdf_void_callback)(wkhtmltopdf_converter * converter);

int wkhtmltopdf_init(int use_graphics);
int wkhtmltopdf_deinit();
int wkhtmltopdf_extended_qt();
const char * wkhtmltopdf_version();

wkhtmltopdf_global_settings * wkhtmltopdf_create_global_settings();
void wkhtmltopdf_destroy_global_settings(wkhtmltopdf_global_settings *);

wkhtmltopdf_object_settings * wkhtmltopdf_create_object_settings();
void wkhtmltopdf_destroy_object_settings(wkhtmltopdf_object_settings *);

int wkhtmltopdf_set_global_setting(wkhtmltopdf_global_settings * settings, const char * name, const char * value);
int wkhtmltopdf_get_global_setting(wkhtmltopdf_global_settings * settings, const char * name, char * value, int vs);
int wkhtmltopdf_set_object_setting(wkhtmltopdf_object_settings * settings, const char * name, const char * value);
int wkhtmltopdf_get_object_setting(wkhtmltopdf_object_settings * settings, const char * name, char * value, int vs);


wkhtmltopdf_converter * wkhtmltopdf_create_converter(wkhtmltopdf_global_settings * settings);
void wkhtmltopdf_destroy_converter(wkhtmltopdf_converter * converter);

void wkhtmltopdf_set_debug_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_str_callback cb);
void wkhtmltopdf_set_info_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_str_callback cb);
void wkhtmltopdf_set_warning_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_str_callback cb);
void wkhtmltopdf_set_error_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_str_callback cb);
void wkhtmltopdf_set_phase_changed_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_void_callback cb);
void wkhtmltopdf_set_progress_changed_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_int_callback cb);
void wkhtmltopdf_set_finished_callback(wkhtmltopdf_converter * converter, wkhtmltopdf_int_callback cb);


int wkhtmltopdf_convert(wkhtmltopdf_converter * converter);
void wkhtmltopdf_add_object(
 wkhtmltopdf_converter * converter, wkhtmltopdf_object_settings * setting, const char * data);

int wkhtmltopdf_current_phase(wkhtmltopdf_converter * converter);
int wkhtmltopdf_phase_count(wkhtmltopdf_converter * converter);
const char * wkhtmltopdf_phase_description(wkhtmltopdf_converter * converter, int phase);
const char * wkhtmltopdf_progress_string(wkhtmltopdf_converter * converter);
int wkhtmltopdf_http_error_code(wkhtmltopdf_converter * converter);
long wkhtmltopdf_get_output(wkhtmltopdf_converter * converter, const unsigned char **);

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_pdf_b6543bab41504ff7(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_pdf_b6543bab41504ff7(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_init_pdf_b6543bab41504ff7(intgo _swig_go_0) {
  int arg1 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (int)wkhtmltopdf_init(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_deinit_pdf_b6543bab41504ff7() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)wkhtmltopdf_deinit();
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_extended_qt_pdf_b6543bab41504ff7() {
  int result;
  intgo _swig_go_result;
  
  
  result = (int)wkhtmltopdf_extended_qt();
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_wkhtmltopdf_version_pdf_b6543bab41504ff7() {
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (char *)wkhtmltopdf_version();
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


wkhtmltopdf_global_settings *_wrap_wkhtmltopdf_create_global_settings_pdf_b6543bab41504ff7() {
  wkhtmltopdf_global_settings *result = 0 ;
  wkhtmltopdf_global_settings *_swig_go_result;
  
  
  result = (wkhtmltopdf_global_settings *)wkhtmltopdf_create_global_settings();
  *(wkhtmltopdf_global_settings **)&_swig_go_result = (wkhtmltopdf_global_settings *)result; 
  return _swig_go_result;
}


void _wrap_wkhtmltopdf_destroy_global_settings_pdf_b6543bab41504ff7(wkhtmltopdf_global_settings *_swig_go_0) {
  wkhtmltopdf_global_settings *arg1 = (wkhtmltopdf_global_settings *) 0 ;
  
  arg1 = *(wkhtmltopdf_global_settings **)&_swig_go_0; 
  
  wkhtmltopdf_destroy_global_settings(arg1);
  
}


wkhtmltopdf_object_settings *_wrap_wkhtmltopdf_create_object_settings_pdf_b6543bab41504ff7() {
  wkhtmltopdf_object_settings *result = 0 ;
  wkhtmltopdf_object_settings *_swig_go_result;
  
  
  result = (wkhtmltopdf_object_settings *)wkhtmltopdf_create_object_settings();
  *(wkhtmltopdf_object_settings **)&_swig_go_result = (wkhtmltopdf_object_settings *)result; 
  return _swig_go_result;
}


void _wrap_wkhtmltopdf_destroy_object_settings_pdf_b6543bab41504ff7(wkhtmltopdf_object_settings *_swig_go_0) {
  wkhtmltopdf_object_settings *arg1 = (wkhtmltopdf_object_settings *) 0 ;
  
  arg1 = *(wkhtmltopdf_object_settings **)&_swig_go_0; 
  
  wkhtmltopdf_destroy_object_settings(arg1);
  
}


intgo _wrap_wkhtmltopdf_set_global_setting_pdf_b6543bab41504ff7(wkhtmltopdf_global_settings *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  wkhtmltopdf_global_settings *arg1 = (wkhtmltopdf_global_settings *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_global_settings **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)wkhtmltopdf_set_global_setting(arg1,(char const *)arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_get_global_setting_pdf_b6543bab41504ff7(wkhtmltopdf_global_settings *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3) {
  wkhtmltopdf_global_settings *arg1 = (wkhtmltopdf_global_settings *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_global_settings **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (int)_swig_go_3; 
  
  result = (int)wkhtmltopdf_get_global_setting(arg1,(char const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_set_object_setting_pdf_b6543bab41504ff7(wkhtmltopdf_object_settings *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2) {
  wkhtmltopdf_object_settings *arg1 = (wkhtmltopdf_object_settings *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_object_settings **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  result = (int)wkhtmltopdf_set_object_setting(arg1,(char const *)arg2,(char const *)arg3);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_get_object_setting_pdf_b6543bab41504ff7(wkhtmltopdf_object_settings *_swig_go_0, _gostring_ _swig_go_1, _gostring_ _swig_go_2, intgo _swig_go_3) {
  wkhtmltopdf_object_settings *arg1 = (wkhtmltopdf_object_settings *) 0 ;
  char *arg2 = (char *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_object_settings **)&_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  arg4 = (int)_swig_go_3; 
  
  result = (int)wkhtmltopdf_get_object_setting(arg1,(char const *)arg2,arg3,arg4);
  _swig_go_result = result; 
  free(arg2); 
  free(arg3); 
  return _swig_go_result;
}


wkhtmltopdf_converter *_wrap_wkhtmltopdf_create_converter_pdf_b6543bab41504ff7(wkhtmltopdf_global_settings *_swig_go_0) {
  wkhtmltopdf_global_settings *arg1 = (wkhtmltopdf_global_settings *) 0 ;
  wkhtmltopdf_converter *result = 0 ;
  wkhtmltopdf_converter *_swig_go_result;
  
  arg1 = *(wkhtmltopdf_global_settings **)&_swig_go_0; 
  
  result = (wkhtmltopdf_converter *)wkhtmltopdf_create_converter(arg1);
  *(wkhtmltopdf_converter **)&_swig_go_result = (wkhtmltopdf_converter *)result; 
  return _swig_go_result;
}


void _wrap_wkhtmltopdf_destroy_converter_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  
  wkhtmltopdf_destroy_converter(arg1);
  
}


void _wrap_wkhtmltopdf_set_debug_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_str_callback arg2 = (wkhtmltopdf_str_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_str_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_debug_callback(arg1,arg2);
  
}


void _wrap_wkhtmltopdf_set_info_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_str_callback arg2 = (wkhtmltopdf_str_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_str_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_info_callback(arg1,arg2);
  
}


void _wrap_wkhtmltopdf_set_warning_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_str_callback arg2 = (wkhtmltopdf_str_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_str_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_warning_callback(arg1,arg2);
  
}


void _wrap_wkhtmltopdf_set_error_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_str_callback arg2 = (wkhtmltopdf_str_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_str_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_error_callback(arg1,arg2);
  
}


void _wrap_wkhtmltopdf_set_phase_changed_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_void_callback arg2 = (wkhtmltopdf_void_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_void_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_phase_changed_callback(arg1,arg2);
  
}


void _wrap_wkhtmltopdf_set_progress_changed_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_int_callback arg2 = (wkhtmltopdf_int_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_int_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_progress_changed_callback(arg1,arg2);
  
}


void _wrap_wkhtmltopdf_set_finished_callback_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, void* _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_int_callback arg2 = (wkhtmltopdf_int_callback) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_int_callback *)&_swig_go_1; 
  
  wkhtmltopdf_set_finished_callback(arg1,arg2);
  
}


intgo _wrap_wkhtmltopdf_convert_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  
  result = (int)wkhtmltopdf_convert(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_wkhtmltopdf_add_object_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, wkhtmltopdf_object_settings *_swig_go_1, _gostring_ _swig_go_2) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  wkhtmltopdf_object_settings *arg2 = (wkhtmltopdf_object_settings *) 0 ;
  char *arg3 = (char *) 0 ;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(wkhtmltopdf_object_settings **)&_swig_go_1; 
  
  arg3 = (char *)malloc(_swig_go_2.n + 1);
  memcpy(arg3, _swig_go_2.p, _swig_go_2.n);
  arg3[_swig_go_2.n] = '\0';
  
  
  wkhtmltopdf_add_object(arg1,arg2,(char const *)arg3);
  
  free(arg3); 
}


intgo _wrap_wkhtmltopdf_current_phase_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  
  result = (int)wkhtmltopdf_current_phase(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_phase_count_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  
  result = (int)wkhtmltopdf_phase_count(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


_gostring_ _wrap_wkhtmltopdf_phase_description_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, intgo _swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  int arg2 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (char *)wkhtmltopdf_phase_description(arg1,arg2);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


_gostring_ _wrap_wkhtmltopdf_progress_string_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  char *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  
  result = (char *)wkhtmltopdf_progress_string(arg1);
  _swig_go_result = Swig_AllocateString((char*)result, result ? strlen((char*)result) : 0); 
  return _swig_go_result;
}


intgo _wrap_wkhtmltopdf_http_error_code_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  
  result = (int)wkhtmltopdf_http_error_code(arg1);
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_wkhtmltopdf_get_output_pdf_b6543bab41504ff7(wkhtmltopdf_converter *_swig_go_0, char **_swig_go_1) {
  wkhtmltopdf_converter *arg1 = (wkhtmltopdf_converter *) 0 ;
  unsigned char **arg2 = (unsigned char **) 0 ;
  long result;
  long long _swig_go_result;
  
  arg1 = *(wkhtmltopdf_converter **)&_swig_go_0; 
  arg2 = *(unsigned char ***)&_swig_go_1; 
  
  result = (long)wkhtmltopdf_get_output(arg1,(unsigned char const **)arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

