name: Makefile CI

permissions:
  contents: read

on:
  push: {}
  pull_request:
    branches: [ $default-branch ]

jobs:

  build-and-test:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v6

    - name: Install WeasyPrint and diff-pdf
      run: |
        brew update
        brew install weasyprint diff-pdf

    - name: Install wkhtmltopdf
      run: |
        wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-2/wkhtmltox-0.12.6-2.macos-cocoa.pkg
        sudo installer -pkg wkhtmltox-0.12.6-2.macos-cocoa.pkg -target /

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v6
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Test Exports
      run: make test-exports
