name: Makefile CI

permissions:
  contents: read

on:
  push: {}
  pull_request:
    branches: [ $default-branch ]

jobs:

  build-and-test:
    strategy:
      matrix:
        os:
        - macos-latest
        - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:

    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Vet
      run: make vet

    - name: Build (macOS)
      if: runner.os == 'macOS'
      run: make

    - name: Build (Linux)
      if: runner.os == 'Linux'
      run: make bin/bagoup

    - name: Install wkhtmltopdf (macOS)
      if: runner.os == 'macOS'
      run: |
        gh release download 0.12.6-2 --repo wkhtmltopdf/packaging --pattern "wkhtmltox-0.12.6-2.macos-cocoa.pkg"
        sudo installer -pkg wkhtmltox-0.12.6-2.macos-cocoa.pkg -target /

    - name: Install wkhtmltopdf (Linux)
      if: runner.os == 'Linux'
      run: |
        gh release download 0.12.6.1-3 --repo wkhtmltopdf/packaging --pattern "wkhtmltox_0.12.6.1-3.jammy_amd64.deb"
        sudo apt-get update -y
        sudo apt-get install -y ./wkhtmltox_0.12.6.1-3.jammy_amd64.deb

    - name: Test
      run: make test

    - name: Upload Code Coverage
      uses: codecov/codecov-action@v6
      with:
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: ${{ matrix.os }}

    - name: Install WeasyPrint, poppler, and imagemagick (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install weasyprint poppler imagemagick ghostscript

    - name: Install WeasyPrint, emojis, poppler, and imagemagick (Linux)
      if: runner.os == 'Linux'
      run: |
        pipx install weasyprint
        sudo apt-get install -y fonts-noto-color-emoji poppler-utils ghostscript
        gh release download --latest --repo ImageMagick/ImageMagick --pattern "ImageMagick-*-gcc-x86_64.AppImage" --output magick
        chmod +x magick
        sudo mv magick /usr/local/bin/magick

    - name: Test Exports
      id: test-exports
      run: make test-exports

    - name: Upload Test Export Artifacts
      if: always() && steps.test-exports.outcome == 'failure'
      uses: actions/upload-artifact@v7
      with:
        name: test-exports-${{ matrix.os }}
        path: |
          test-exports/**
        if-no-files-found: error
